language: go
go:
- 1.10.3
deploy:
  provider: releases
  api_key:
    secure: cHsUd4C6mIWYie8yLpaKhz1vW55j6einuhtkZYwBCYoQm2uChJAu38YkLHWR4SeR50mHtaw9RESxHpsoqqNZwzxdgjU1OEiUG+R5qC6zHuSioWO5ALFxSWpuDoeqz4oipD4t716XweflDn5d/7f8+qyQjqmHvYGJn1M0UI8Isv2mZp1KUJAgwNw7CC6dqX+RjNEIqHxVX45TqzxoH+M3l5PADSYYSA1UC1t1Jrj+b0mZKCKQzH6DAmbbvHagRvFssMB2JpR4rBhCTUy0Mama0AdsPgCg5hEiUTkvRhdF+gybIrnGHUHMHUsFjegRz7QwcrSkMAGfL1Z0YXkWubOZqXa5aEX6zi6oajmn78UBq5G6AnoY+d7DHk+bR0ZOlLP36c/WDnXWvmRZH70D1JwsHyhqF7pX322/cP/7Eq+yS1LZoIBm2lbZc+kWqLNoGdzFiZf1u9sqDK/5IAAW6OHEbWmo+cjI4pLW/YSSxTAYyHJ8468kDUYsjKnegPw/IX7FMQwLFPqx+P51B//VY/FKHaAM66AkS7EswX3BGdpDQwaY8gHfOeZLQdrRv8gs36mT8ZYAV0zLeJaVjwReuV/gB9on18PWaVwXIl6jtcdQT+AUmxjwBW6TrB4ELtN6lGOXJsvqhzxh9pLphVuNxv3x6ueIO4fM+Sde8WqjFrMNvmE=
  file: build/release.tar.gz
  on:
    repo: ncipollo/fnew
    tags: true
