language: go
go:
- 1.10.3
deploy:
  provider: releases
  api_key:
    secure: tN+5WoOrzhth+RWZEh46iMSYYJgtkg/B3POC5Ik1Km4f4pPf81LtLo+jtzde6zckOI2uG+fyBD3XfjNiy8o5Gks3vcbhYrJIBTDByPED/gPjb96Fz5mLICqtF+mB3dGMXuKwmRL445O10YvevvJn2I1JOhXVyMuH651pwx2ASiOcmt9zOvB8ah0EZOj5x7pthNLTg+Jh7Jo5PbSjA7iV5/nikaZCKArHS6KumS1UPsiMJmLqsZVQLqOtqcBq6DYHwJuv9UjqHqWHF4JLDOKt87UtpZAYLkhfVrxA/faQ0gXf2apBnNB1UtuycIfGmERt6Xah08kRwxHu5YEy7E9w9kqcHRjryxeOSAWjzH2OTAO/u8ll5YUlcxWn81YD5Xe7/MqMKbSaP+c2MBA/Tfd3r5ype9DFcEO/6mEoVmHXNG6YviPOLEr8idd7Cs/P2oQ8F0fXyRyL4BeySr1XGuL2Z0EdDxh8cBwbXchZGSnzNO0V6GID9ou3Li67H9NKCdcJCAbbdPiJSZWHv1V2ggWwGbgzMEJy/z9Ze23rwT9m0YkzoK70ywyFzBqcW3SkSpThnG3UAkQZEsawPCBDfluV/s8rFRepZ8UpkrNjxpy+HM+Y79+GblYCUztuPYWKxQjvovrYLpSbcGT0OCShjuQqX88yhUVW3a/6digouRY9VW0=
  file: build/release.tar.gz
